language: C
script: make
before_install:
 - sudo apt-get install ncurses-dev
matrix:
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env:
      - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
  - os: linux
    compiler: clang
