language: C
script: make
env:
  global:
    #secure: nxgJyvcOYZWGxHYPMMioaLJ25p5mWSTE4dEK5mNZrmRLGm+tTqB1SIfDSGYRO4U/nisLt97JWM4fMv9sly7Q29l79PkTgT4PZvR3DoQV+FPoeZnTmAcj+iAHfzRycSVlxwmp0zdhlbiZ4pHMKYjGrg0Br1XJyosRbsG+JRVbbhwKFgXwafjS6i4C2ILYxuCViBHtwaZ2J5lPIBEalUwhlPy/ZT4d+Uc8WXqKYOGNMYrqtJ+KQRBiXmcHdl9cACSTpt8sBXaMixIYUu1pUpVTitVa0E6gmt76qpVclZ44bdNbkqy5PCHgeeGXyvFmAyOLIZwGmPzOww7Odow35W4tQj3Mmt0rY9FCxjMmMbYE7uscC7hoYXZDLVFRJYWaBgEV17rotNn0KYLCEsttFV87iu5HDYhI7bmHtdUd9+vtXEOhg6U0xWyyD5qnYWekBrvrYdCP0mpgGfHb36Njxtw7AhB1zxVx2g15jjFA7WHgzPtWevzwlDLo4IlHZ6y8Lj4nXLDKTn/vXXrhXNJBM76e5WLYzBft2G0dOtgRRPIqk1U4gcIkCojLm7Qs8LIVs3nrm6Zb6SxUW1Wp0JtdCjX2DzIXEYkch+xSeCSee1WjJwIMyuNh+KBdRvyw8MbGO0pXdMT8UeOf66eBO2n6WGAMV4qffKEdmKBs8WP3blRuTzo=
    secure: Upk+zzTa+L79Jqhc87cWJ7ig3rBUrMSyooonYgcR7qOw1jZkRZmpNWBntCDC9k75wWbvkkcWsU2Xuq8Vo9DHoMLmK8W4JYV7m4dTOjgbvbl4986wNOrhLx86Os3h9/tGY0i2+ymmUD4xFfiVL0zKJeRhrg3Imf4U6xpxESg2r/kEGa+sLVJs+NWfuTmVSXbe3Qj11ZCrF9XN9yCH1APk90Lf/a+vuEu58SKyHvoDMqD92OwfcvklBO+9u5r2PAgE1eqilWzsri2+1Gm2Th0ujTIuvud2G1t5Q73y8ELJmZWaKDA/R4VbOMemwPppsfKjbz5eRPGbvCXez/FZyBYX/3xOoviOKCBNdE64wwje++yceGGDSDWL+2PBkNX545vkypX0ERVCd91j7s7pv8Bi8rEXGgMpmY+8rdEH1aO3BgvdJNawyI+bR6KlAobDxN6pI+Bf/+Ej4djGUatjoEuTzTIaerY5v8VxMIUllARgM71OadVW3AH0eZKrYRgUhAdBAfWiJae4koK+EL6CQDwCC5JdjlyNzo1FOmYK/wHBJ0/Hsimm54HDn/pJZAz2+mssT1FXhwZtfmhEtPYREFYZBIHMPuF5oR2FqnDUR03TUEqVEhegq6wPAUXipRnywF0d2TwwMtiB1xUQKiu7NTedDtiUk6LNn6kFS4JVd4P9TmI=
before_install:
- sudo apt-get install ncurses-dev
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- eval ${MATRIX_EVAL}
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
    env:
    - MATRIX_EVAL="CC=gcc-4.9 CXX=g++-4.9"
  - os: linux
    compiler: clang
    addons:
      coverity_scan:
        project:
          #name: W8BSD/bsdtty
          name: bsdtty
          description: Console RTTY client
        notification_email: shurd@sasktel.net
        build_command: make
        branch_pattern: master
