language: C
script: make
before_install:
 - eval "${MATRIX_EVAL}"
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
      before_install:
       - sudo apt-get install ncurses-dev
    - os: linux
      compiler: clang
      before_install:
       - sudo apt-get install ncurses-dev
    - os: osx
