language: C
script: make
env:
  global:
    secure: nxgJyvcOYZWGxHYPMMioaLJ25p5mWSTE4dEK5mNZrmRLGm+tTqB1SIfDSGYRO4U/nisLt97JWM4fMv9sly7Q29l79PkTgT4PZvR3DoQV+FPoeZnTmAcj+iAHfzRycSVlxwmp0zdhlbiZ4pHMKYjGrg0Br1XJyosRbsG+JRVbbhwKFgXwafjS6i4C2ILYxuCViBHtwaZ2J5lPIBEalUwhlPy/ZT4d+Uc8WXqKYOGNMYrqtJ+KQRBiXmcHdl9cACSTpt8sBXaMixIYUu1pUpVTitVa0E6gmt76qpVclZ44bdNbkqy5PCHgeeGXyvFmAyOLIZwGmPzOww7Odow35W4tQj3Mmt0rY9FCxjMmMbYE7uscC7hoYXZDLVFRJYWaBgEV17rotNn0KYLCEsttFV87iu5HDYhI7bmHtdUd9+vtXEOhg6U0xWyyD5qnYWekBrvrYdCP0mpgGfHb36Njxtw7AhB1zxVx2g15jjFA7WHgzPtWevzwlDLo4IlHZ6y8Lj4nXLDKTn/vXXrhXNJBM76e5WLYzBft2G0dOtgRRPIqk1U4gcIkCojLm7Qs8LIVs3nrm6Zb6SxUW1Wp0JtdCjX2DzIXEYkch+xSeCSee1WjJwIMyuNh+KBdRvyw8MbGO0pXdMT8UeOf66eBO2n6WGAMV4qffKEdmKBs8WP3blRuTzo=
before_install:
- sudo apt-get install ncurses-dev
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- eval ${MATRIX_EVAL}
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.9
    env:
    - MATRIX_EVAL="CC=gcc-4.9 CXX=g++-4.9"
  - os: linux
    compiler: clang
    addons:
      coverity_scan:
        project:
          name: W8BSD/bsdtty
          description: Console RTTY client
        notification_email: shurd@sasktel.net
        build_command: make
        branch_pattern: master
